config/routes.rb
Rails.application.routes.draw do
  resources :programminglanguages
  resources :rooms
  resources :messages
  devise_for :users
  root "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/programminglanguage.rb
class Programminglanguage < ApplicationRecord
end

app/controllers/programminglanguages_controller.rb
class ProgramminglanguagesController < ApplicationController
  before_action :set_programminglanguage, only: %i[ show edit update destroy ]

  # GET /programminglanguages or /programminglanguages.json
  def index
    @programminglanguages = Programminglanguage.all
  end

  # GET /programminglanguages/1 or /programminglanguages/1.json
  def show
  end

  # GET /programminglanguages/new
  def new
    @programminglanguage = Programminglanguage.new
  end

  # GET /programminglanguages/1/edit
  def edit
  end

  # POST /programminglanguages or /programminglanguages.json
  def create
    @programminglanguage = Programminglanguage.new(programminglanguage_params)

    respond_to do |format|
      if @programminglanguage.save
        format.html { redirect_to programminglanguage_url(@programminglanguage), notice: "Programminglanguage was successfully created." }
        format.json { render :show, status: :created, location: @programminglanguage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @programminglanguage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programminglanguages/1 or /programminglanguages/1.json
  def update
    respond_to do |format|
      if @programminglanguage.update(programminglanguage_params)
        format.html { redirect_to programminglanguage_url(@programminglanguage), notice: "Programminglanguage was successfully updated." }
        format.json { render :show, status: :ok, location: @programminglanguage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @programminglanguage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programminglanguages/1 or /programminglanguages/1.json
  def destroy
    @programminglanguage.destroy

    respond_to do |format|
      format.html { redirect_to programminglanguages_url, notice: "Programminglanguage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programminglanguage
      @programminglanguage = Programminglanguage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def programminglanguage_params
      params.require(:programminglanguage).permit(:name, :printres)
    end
end

app/helpers/programminglanguages_helper.rb
module ProgramminglanguagesHelper
end

app/views/programminglanguages/_form.html.erb
<%= form_with(model: programminglanguage) do |form| %>
  <% if programminglanguage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(programminglanguage.errors.count, "error") %> prohibited this programminglanguage from being saved:</h2>

      <ul>
        <% programminglanguage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :printres, style: "display: block" %>
    <p>entrez le "%s" là où on insert le code dans une seule ligne (bash)</p>
    <p>p.s.
    Pour enregistrer les guillemets ' et " pour le code python, nous pouvons construire le bloc avec EOF

    <code>
    c=&#96;cat <<EOF
    print(122)
    EOF&#96;
    python -c "$c"
    </code>
    ou pour l'exception avec python:
    <code>
      c=&#96;cat <<EOF 
      try:
        %s
        except Exception as e:
          print(e)
          EOF&#96;
          python3 -c "$c"
    </code>


    </p>
    <%= form.text_area :printres %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/programminglanguages/_programminglanguage.html.erb
<div id="<%= dom_id programminglanguage %>">
  <p>
    <strong>Name:</strong>
    <%= programminglanguage.name %>
  </p>

  <p>
    <strong>Printres:</strong>
    <%= simple_format(programminglanguage.printres.gsub("`","&#96;").html_safe).html_safe %>
  </p>

</div>

app/views/programminglanguages/edit.html.erb
<h1>Editing programminglanguage</h1>

<%= render "form", programminglanguage: @programminglanguage %>

<br>

<div>
  <%= link_to "Show this programminglanguage", @programminglanguage %> |
  <%= link_to "Back to programminglanguages", programminglanguages_path %>
</div>

app/views/programminglanguages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Programminglanguages</h1>

<div id="programminglanguages">
  <% @programminglanguages.each do |programminglanguage| %>
    <%= render programminglanguage %>
    <p>
      <%= link_to "Show this programminglanguage", programminglanguage %>
    </p>
  <% end %>
</div>

<%= link_to "New programminglanguage", new_programminglanguage_path %>

app/views/programminglanguages/new.html.erb
<h1>New programminglanguage</h1>

<%= render "form", programminglanguage: @programminglanguage %>

<br>

<div>
  <%= link_to "Back to programminglanguages", programminglanguages_path %>
</div>

app/views/programminglanguages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @programminglanguage %>

<div>
  <%= link_to "Edit this programminglanguage", edit_programminglanguage_path(@programminglanguage) %> |
  <%= link_to "Back to programminglanguages", programminglanguages_path %>

  <%= button_to "Destroy this programminglanguage", @programminglanguage, method: :delete %>
</div>